package org.proyectobdmotos.services.exceptions;

public enum BusinessErrorCode {
    CLIENTE_NO_ENCONTRADO,
    MOTO_NO_ENCONTRADA,
    MOTO_NO_DISPONIBLE,
    CONTRATO_NO_ENCONTRADO,
    CONTRATO_YA_FINALIZADO,
    CONTRATO_FECHA_ENTREGA_INVALIDA,
    CONTRATO_KM_INVALIDO,
    CONTRATO_VALIDACION_FALLIDA
}
