package org.proyectobdmotos.services.exceptions;

public enum BusinessErrorCode {
    CLIENTE_NO_ENCONTRADO,
    MOTO_NO_ENCONTRADA,
    MOTO_NO_DISPONIBLE,
    CONTRATO_NO_ENCONTRADO,
    CONTRATO_YA_FINALIZADO,
    CONTRATO_FECHA_ENTREGA_INVALIDA,
    CONTRATO_KM_INVALIDO,
    CONTRATO_VALIDACION_FALLIDA,
    CAMPO_REQUERIDO,
    FORMATO_INVALIDO,
    RANGO_INVALIDO,
    FECHA_INVALIDA,
    NUMERO_NO_POSITIVO,
    SIN_CONEXION_BD,
    UNICIDAD_INVALIDA,
    ID_INVALIDO,
    CREDENCIALES_INVALIDAS,
    USUARIO_YA_EXISTE,
    EMAIL_YA_EXISTE,
    TEXTO_INVALIDO,
    MOTO_TIENE_CONTRATOS
}
